# Generated by Django 5.1.2 on 2024-11-16 07:25

import ftp.stroge_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftp',
            name='image',
            field=models.ImageField(storage=ftp.stroge_backends.FtpStorage(), upload_to=''),
        ),
    ]
